# Generated by Django 3.2.3 on 2021-05-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchinfo',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='branchinfo',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
    ]
